### ISSUE TITLE
Bintray settings cause problems in dbuild

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt-testng-interface#4]
While working on adding sbt-testng-interface to community build I ran into [a problem](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/113/console) with publishing:

```
[sbt-testng-interface] Publishing: sbt-testng-interface
[sbt-testng-interface] bintray-sbt requires your bintray credentials.
[sbt-testng-interface] [warn] Credentials file /home/jenkinsdbuild3/.bintray/.credentials does not exist
[sbt-testng-interface] Enter bintray username: java.util.NoSuchElementException: None.get
[sbt-testng-interface] 	at scala.None$.get(Option.scala:313)
[sbt-testng-interface] 	at scala.None$.get(Option.scala:311)
```

It looks like bintray sbt plugin overrides the default publishing mechanism and that trips dbuild. Not sure if it's dbuild, sbt-testng-interface or bintray plugin that requires fixing. For now, I'm logging this ticket to have a point of reference.

**Comment by gkossakowski** [comment]
I turns out that this is a problem with dbuild. See typesafehub/dbuild#158. Closing this issue.

**Comment by jmhofer** [comment]
Ok, good to know, thanks.
